# Generated by Django 4.2.26 on 2025-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['file', 'user'], name='storage_dow_file_id_0f689c_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['user', 'timestamp'], name='storage_dow_user_id_307a68_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['file', 'timestamp'], name='storage_dow_file_id_873d7d_idx'),
        ),
    ]
